In [1]:
import numpy as np

In [7]:
#Problem 1: Normalization problem

x = np.random.random((5,5))

In [12]:
x_normalized = (x-x.mean()) /np.std(x)

In [9]:
np.save("x_normalized.npy", x_normalized)

In [11]:
print ("Original x (5x5):\n",x)

Original x (5x5):
 [[0.75928255 0.88237251 0.35442043 0.3574337  0.2011563 ]
 [0.34524322 0.84892154 0.18081599 0.97527632 0.73563713]
 [0.97226582 0.70754737 0.15784472 0.46789611 0.20060062]
 [0.8409555  0.05335254 0.0844473  0.74892317 0.22149244]
 [0.85802114 0.87897624 0.76228927 0.89606919 0.41144278]]


In [13]:
print ("\nNormalized x:\n", x_normalized)


Normalized x:
 [[ 0.65551726  1.05265035 -0.65071555 -0.64099365 -1.14520152]
 [-0.6803246   0.94472531 -1.21082677  1.35239191  0.5792285 ]
 [ 1.34267894  0.4886007  -1.28494046 -0.28460165 -1.14699435]
 [ 0.91902398 -1.62207036 -1.52174732  0.62209411 -1.07958971]
 [ 0.97408395  1.04169273  0.66521804  1.09684084 -0.46674067]]


In [15]:
#Problem 2: Divisible by 3 problem

a = np.arange(1,101) ** 2

In [22]:
a = a.reshape(10,10)

In [17]:
div_by_3 = a[a%3==0]

In [25]:
np.save("div_by_3.npy", div_by_3)

In [26]:
print ("\n10x10 Array of Squares (a):\n",a)


10x10 Array of Squares (a):
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [27]:
print ("\nElements Divisible by 3:\n",div_by_3)


Elements Divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
